### PR TITLE
Docs improve

### PR DESCRIPTION
**Pull request by stokito**
This changes would safe me time. Easy to build with `make build` and run a demo.
Docs made more clear.

### CODE REVIEW

**Comment by tg123** [comment]
thanks for the pr

1 makefile is good, but have to keep it up to date. current build is via gorelease, any future update may make makefile stale.
2 key can be generated via `--server-key-generate-mode=notexist`, no need to put a fake key in the repo
3 maybe using docker-compose to start a demo if doc is not clear enough

**Comment by stokito** [comment]
The makefile is really just same steps as described in the readme. 
It's main goal is to build plugins but then debug in Goland.
The goreleaser is an additional tool to install and learn which I don\t need for now.

I just made changes that might simplify learning for me

**Comment by tg123** [comment]
there is a devcontainer.json for vscode, i do not have goland not sure if makefile is required
but i am open to add makefile, as building plugins need too many args to `go build`

integrate makefile with https://github.com/tg123/sshpiper/blob/master/Dockerfile#L12?

**Comment by stokito** [comment]
Well, the purpose of the Makefile is just to show a simplest commands to build it locally. No need to integrate to with Docker. It can be just as an option.
If you feel not comfortable with it then you can skip the last commit

**Comment by tg123** [comment]
i mean call `make` inside dockerfile to ensure makefile is up to date

**Comment by stokito** [comment]
Not sure, but rather no. They are used for different purposes.

**Pull request closed without merging**
