### PR TITLE
Add support for kubenetes

### PR DESCRIPTION
**Pull request by lermit**
Hi

First of all thank for you work !

We just add support of a kubernetes CRD named SshPipe allowing dynamic configuration.

Some example are présent in the upstream/kubernetes/example folder :)

Fill free to comment and have a nice weekend.

Regards

### CODE REVIEW

**Comment by tg123** [comment]
AWESOME IDEA!
Thanks

**Comment by rjbaat** [comment]
@lermit awesome work! 
I am wondering if you can add the config options to map to a service in a different namespace. If iam right its now only possible to point to a service in the same namespace as where sshpiper is installed in. Is that correct?

**Comment by rjbaat** [comment]
@lermit is there an option to get this to work with ssh public keys? I read this can be done when using the private key in the sshpiper container. Is there a way to add the private key of the user of the upstream server to the ssh pipe manifest for example?

**Comment by lermit** [comment]
Hi Ruben


I'm from now on holidays. I'll check that in about 2weeks :)

Regards

**Comment by lermit** [comment]
I'm using this in different namespace, so it should be possible:)

If multi namespace network connection is allowed of course ;)

**Comment by rjbaat** [comment]
Cool!
That would be awesome.
Have a nice holiday!

**Comment by automaticgiant-ml** [comment]
@lermit it looks like this upstream plugin doesnt support public key auth but im not sure.
i think i might need to configure the upstreams with a different plugin, or patch in the functionality.

**Pull request merged**
